-- Contacto basico
INSERT INTO system.contactos (correo, codigo_postal, colonia, num_externo, num_interno, primera_calle, segunda_calle, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('ejemplo1@email.com', '12345', 'Ejemplo Colonia', '123', 'A', 'Calle Ejemplo 1', 'Calle Ejemplo 2', 'Ejemplo1', 'Pérez', '1990-01-01', 'Juan', '1234567890');
INSERT INTO system.contactos (correo, codigo_postal, colonia, num_externo, num_interno, primera_calle, segunda_calle, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('ejemplo2@email.com', '54321', 'Otra Colonia', '321', 'B', 'Calle Otro 1', 'Calle Otro 2', 'Ejemplo2', 'Gómez', '1985-05-15', 'María', '9876543210');
INSERT INTO system.contactos (correo, codigo_postal, colonia, num_externo, num_interno, primera_calle, segunda_calle, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('ejemplo3@email.com', '67890', 'Nueva Colonia', '456', 'C', 'Calle Nueva 1', 'Calle Nueva 2', 'Ejemplo3', 'López', '1988-12-25', 'Ana', '4567890123');
-- Contacto con informacion adicional
INSERT INTO system.contactos (correo, codigo_postal, colonia, num_externo, num_interno, primera_calle, segunda_calle, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('otro1@email.com', '13579', 'Otro Colonia', '111', 'A', 'Calle Otro 1', 'Calle Otro 2', 'Otro1', 'Martínez', '1992-08-20', 'Pedro', '3216549870');
INSERT INTO system.contactos (correo, codigo_postal, colonia, num_externo, num_interno, primera_calle, segunda_calle, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('otro2@email.com', '98765', 'Otra Colonia', '999', 'B', 'Calle Nuevo 1', 'Calle Nuevo 2', 'Otro2', 'Hernández', '1980-04-10', 'Luis', '7894561230');
INSERT INTO system.contactos (correo, codigo_postal, colonia, num_externo, num_interno, primera_calle, segunda_calle, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('otro3@email.com', '24680', 'Colonia Nueva', '222', 'C', 'Calle Vieja 1', 'Calle Vieja 2', 'Otro3', 'Sánchez', '1975-06-30', 'Marcela', '1593578520');
-- Contacto sin informacion de direccion
INSERT INTO system.contactos (correo, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('sininfo1@email.com', 'SinInfo1', 'García', '1976-03-15', 'Laura', '5559876543');
INSERT INTO system.contactos (correo, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('sininfo2@email.com', 'SinInfo2', 'Díaz', '1983-11-20', 'Roberto', '5557418529');
INSERT INTO system.contactos (correo, alias, apellido, fecha_cumpleanhos, nombre, num_telefono) VALUES ('sininfo3@email.com', 'SinInfo3', 'Fernández', '1995-09-05', 'Carla', '5553691478');
